version: '3'
services:

  nginx:
      build:
          context: ./docker/nginx
      volumes:
          - ./:/app
      ports:
          - "8080:80"
      depends_on:
          - php-fpm

  php-fpm:
      env_file:
        - docker-compose.env
      build:
          context: ./docker/php
      volumes:
          - ./:/app
      environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=home_work"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      depends_on:
          - mysql

  mysql:
      image: mysql:5.7
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=root"
        - "MYSQL_PASSWORD=root"
        - "MYSQL_DATABASE=home_work"
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "3306:3306"

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"

volumes:
  mysql:
    driver: local