version: '3'
services:

  nginx:
      build:
          context: ./docker/nginx
      volumes:
          - /blog:/app
      ports:
          - "8080:80"
      depends_on:
          - php-fpm

  php-fpm:
      env_file:
        - docker-compose.env
      build:
          context: ./docker/php
      volumes:
          - /blog:/app
      environment:
      - "DB_CONNECTION=${DB_CONNECTION}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      depends_on:
          - mysql

  mysql:
      image: mysql:5.7
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=root"
        - "MYSQL_PASSWORD=root"
        - "MYSQL_DATABASE=home_work"
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "3306:3306"

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"

volumes:
  mysql:
    driver: local